### ISSUE TITLE
Development of cloudmesh-cloud milestone for upcomming class

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#234]

**Comment by laszewsk** [comment]
- [ ] #233 cms cluster command
- [ ] #232 query interface for images
- [ ] #230 query interface for flavors
